application: gae-react-starter
version: 1
runtime: python27
api_version: 1
threadsafe: yes


# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^static/src/.*

handlers:
- url: /static
  static_dir: static
  secure: optional

- url: .*
  static_files: static/app.html
  upload: static/app\.html